{
  "project": {
    "type": "manuscript",
    "output-dir": "_site"
  },
  "metadata-files": [
    "_cse-manuscript.json"
  ],
  "manuscript": {
    "article": "index.qmd"
  },
  "format": {
    "html": {
      "embed-resources": true,
      "theme": "cosmo",
      "fontsize": "16px",
      "toc": false,
      "self-contained-math": true,
      "html-math-method": "mathjax",
      "css": "site.css"
    }
  },
  "execute": {
    "enabled": false
  },
  "keep-md": true
}
