"""Write the result tables of the manuscript and supplement from the retained #154 results.

Usage (from docs/scientific/latex/): python scripts/final_rerun_tables.py
Reads analyses/mea_parameter_bundle/results/final-rerun/ only; writes tables/*.tex.
Values are rounded for display; do not hand-edit the generated files.
"""
import csv
import json
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
RUN = HERE.parents[2] / "analyses/mea_parameter_bundle/results/final-rerun"
TABLES = HERE / "tables"
HEAD = "% Generated by scripts/final_rerun_tables.py from analyses/mea_parameter_bundle/results/final-rerun; do not hand-edit values.\n"
CW, HW, BW, CH = (f"pair/{p}/k_ij" for p in ("carbamate-anion/water", "protonated-monoethanolamine/water",
                                            "bicarbonate-anion/water", "carbamate-anion/protonated-monoethanolamine"))
SLOPE = HW + "/reciprocal_temperature_slope"
SYMBOL = {CW: r"\(k_{\MEACOO,\HtwoO}\)", HW: r"\(k_{\MEAH,\HtwoO}\)", BW: r"\(k_{\HCOthree,\HtwoO}\)",
          CH: r"\(k_{\MEAH,\MEACOO}\)", SLOPE: r"\(b\) (K)"}
FITS = ("F1", "F2", "F3", "F4", "F5", "F6")


def rows(path):
    with (RUN / path).open(newline="") as stream:
        return list(csv.DictReader(stream))


def num(value, digits=2):
    text = f"{float(value):.{digits}f}"
    return text.replace("-", r"\(-\)") if text.startswith("-") else text


def write(name, body):
    (TABLES / name).write_text(HEAD + body)


summary = {r["problem"]: r for r in json.loads((RUN / "fit-summary.json").read_text())}
chosen = {p: next(s for s in r["starts"] if s["start"] == r["lower_complete_start"]) for p, r in summary.items()}
scores = {(r["problem"], r["group"]): r for r in rows("evaluation/scores.csv")}
errors = {(r["problem"], r["coordinate"]): r for r in rows("conditional-standard-errors.csv")}
jakobsen = rows("evaluation/jakobsen-carbonate-share.csv")
density = rows("evaluation/density.csv")


def coordinate(problem, key, digits=4):
    value = chosen[problem]["coordinates"][key]
    if key in chosen[problem]["active_bounds"]:
        return f"{value:+g} (bound)".replace("+", r"\(+\)").replace("-", r"\(-\)")
    return num(value, 1 if key == SLOPE else digits)


def standard_error(problem, key):
    value = errors[(problem, key)]["standard_error"]
    return num(value, 1 if key == SLOPE else 4) if value else "--"


def aard(problem, group):
    return num(scores[(problem, group)]["aard_percent"])


def span(values, digits=2):
    return f"{min(values):.{digits}f}--{max(values):.{digits}f}"


# Main text: deviation and cost summary for F1, F2 and F6.
groups = [("Fitted pressure, 40 and \\SI{60}{\\degreeCelsius}", "fitted", "fit pressure"),
          ("Fitted species, 20--\\SI{60}{\\degreeCelsius}", "fitted", "fit species"),
          ("Matin \\ce{HCO3- + CO3^2-} pool, \\SI{20}{\\degreeCelsius}", "not fitted", "Matin pool report-only"),
          ("Jou et al.\\ pressure, \\SI{80}{\\degreeCelsius}", "outside fit", "Jou 80C"),
          ("Measured pressure, \\SI{80}{\\degreeCelsius}", "outside fit", "canonical 80C 21"),
          ("B\\\"ottinger et al.\\ species, \\SI{80}{\\degreeCelsius}", "outside fit", "Bottinger 80C species"),
          ("Wagner et al.\\ pressure near \\SI{353}{\\kelvin}", "outside fit", "Wagner near 353.15K"),
          ("Wagner et al.\\ pressure near \\SI{392}{\\kelvin}", "outside fit", "Wagner near 392.15K"),
          ("Measured pressure, 100--\\SI{120}{\\degreeCelsius}", "extrapolation", "100-120C"),
          ("Measured pressure, 40--\\SI{80}{\\degreeCelsius}", "pooled", "pooled 40-80C"),
          ("Pressure, 15 wt\\% \\MEA", "transfer", "transfer 15wt%"),
          ("Pressure, 45 wt\\% \\MEA", "transfer", "transfer 45wt%")]
lines = [f"        {label} & {role} & {scores[('F1', key)]['n'] or scores[('F1', key)]['rows']} & "
         + " & ".join(aard(p, key) for p in ("F1", "F2", "F6")) + r" \\" for label, role, key in groups]
ratio = {p: [float(r["ratio"]) for r in jakobsen if r["problem"] == p and r["summary_included"] == "True"]
         for p in ("F1", "F2", "F6")}
deviation = {p: [float(r["deviation_percent"]) for r in density if r["problem"] == p] for p in ("F1", "F2", "F6")}
write("residual_summary.tex", r"""\begin{table}[pos=!htb]
    \centering
    \caption{Deviations and costs of the selected SSM+DS fit (F1), the original Born fit (F2) and the source-law fit (F6), each fitted to the same 141 targets.
    AARD is \(100\,n^{-1}\sum|y_{\mathrm{calc}}/y_{\mathrm{obs}}-1|\) over the stated group, and the cost is \(C=\tfrac12\sum r_j^2\).
    Outside-fit rows are outside the five-parameter fit; the \SI{80}{\degreeCelsius} and higher-temperature data also informed the fixed reaction shifts of F1 and F2 (\cref{sec:data-methods}).
    The 100--\SI{120}{\degreeCelsius} group omits three Xu and Rochelle rows above \SI{393.15}{\kelvin}, the upper limit of the declared reaction-correlation domain.
    The carbonate-share row covers nine Jakobsen et al.\ points at 20 and \SI{40}{\degreeCelsius}; the density row covers four loaded 30 wt\% solutions at 50 and \SI{70}{\degreeCelsius}.}
    \label{tab:residual-summary}
    \begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}X l r r r r@{}}
        \toprule
        Group & Role & \(n\) & F1 & F2 & F6 \\
        \midrule
        \multicolumn{6}{@{}l}{\emph{AARD, \%}} \\
""" + "\n".join(lines) + r"""
        \midrule
        \multicolumn{6}{@{}l}{\emph{Calculated/observed carbonate share of dissolved carbon}} \\
        Jakobsen et al., 20 and \SI{40}{\degreeCelsius} & outside fit & 9 & """ + " & ".join(span(ratio[p]) for p in ("F1", "F2", "F6")) + r""" \\
        \midrule
        \multicolumn{6}{@{}l}{\emph{Density deviation, \%}} \\
        Amundsen et al., loaded & not fitted & 4 & """ + " & ".join(span(deviation[p], 1) for p in ("F1", "F2", "F6")) + r""" \\
        \midrule
        \multicolumn{6}{@{}l}{\emph{Weighted cost}} \\
        Fitted targets & fitted & 141 & """ + " & ".join(num(summary[p]["replay"]["cost"]) for p in ("F1", "F2", "F6")) + r""" \\
        \bottomrule
    \end{tabularx}
\end{table}
""")

# Main text: binary interaction parameters with conditional standard errors.
fitted_rows = []
for key, bounds, note in ((CW, r"\(\pm0.5\)", ""), (HW, r"\(\pm0.5\)", r"; value at \(T_{\mathrm{ref}}\)"),
                          (SLOPE, r"\(\pm1000\)", ""), (BW, r"\(\pm0.5\)", ""), (CH, r"\(\pm1\)", "")):
    fitted_rows.append(f"        {SYMBOL[key]} & Fitted & {bounds} & {coordinate('F1', key)} & {standard_error('F1', key)} & "
                       f"{coordinate('F2', key)} & {standard_error('F2', key)} & This work{note} \\\\")
write("binary_interaction_parameters.tex", r"""\begin{table*}[t]
    \centering
    \caption{Binary dispersion interaction parameters of the selected SSM+DS fit (F1) and the original Born fit (F2), with conditional standard errors (SE).
    The \MEAH--water coefficient is the value at \(T_{\mathrm{ref}}=\SI{313.15}{\kelvin}\) in \cref{eq:kij-temperature}, and \(b\) is its reciprocal-temperature slope.
    SEs condition on each fit's active bounds, use the declared residual scales and treat residuals as independent, although the titration species of one sample are not; they are indicative only.
    A coordinate at a bound has no symmetric interval.
    Pairs of ions with the same charge sign have no dispersion interaction, and every pair not listed has \(k_{ij}=0\).
    Full-precision values are in the parameter file named in the Data and Code Availability statement.}
    \label{tab:binary-interaction-parameters}
    \begin{tabularx}{\textwidth}{@{}lllrrrr>{\raggedright\arraybackslash}X@{}}
        \toprule
        Parameter & Role & Bounds & F1 & SE & F2 & SE & Source or note \\
        \midrule
""" + "\n".join(fitted_rows) + r"""
        \(k_{\MEA,\HtwoO}\) & Fixed & -- & \(-0.0735\) & -- & \(-0.0735\) & -- & Fitted to binary VLE \cite{caiBinaryIsobaricVaporLiquid1996} \\
        \(k_{\COtwo,\HtwoO}\) & Fixed & -- & 0.0133 & -- & 0.0133 & -- & Fitted to binary VLE \cite{kiepeExperimentalDeterminationPrediction2002} \\
        \(k_{\HthreeO,\HtwoO}\) & Fixed & -- & 0.25 & -- & 0.25 & -- & \cite[Table~2]{Held2014} \\
        \(k_{\Hydroxide,\HtwoO}\) & Fixed & -- & \(-0.25\) & -- & \(-0.25\) & -- & \cite[Table~2]{Held2014} \\
        \(k_{\COthree,\HtwoO}\) & Fixed & -- & \(-0.25\) & -- & \(-0.25\) & -- & \cite[Table~2]{Held2014} \\
        \bottomrule
    \end{tabularx}
\end{table*}
""")

# Supplement: the six fits.
form = {"F1": "SSM+DS", "F2": "original Born", "F3": "none", "F4": "SSM+DS", "F5": "original Born", "F6": "SSM+DS"}
role = {"F1": "compared", "F2": "compared", "F3": "compared", "F4": "fitted", "F5": "fitted", "F6": "compared"}
cost_rows = [f"        {p} & {form[p]} & {role[p]} & {summary[p]['replay']['targets']} & {num(summary[p]['replay']['pressure_cost'])} & "
             f"{num(summary[p]['replay']['species_cost'])} & {num(summary[p]['replay']['cost'])} & "
             f"{num(chosen[p]['aard_percent']['pressure'])} & {num(chosen[p]['aard_percent']['species'])} & "
             f"\\num{{{summary[p]['relative_cost_difference']:.1e}}} \\\\" for p in FITS]
coord_rows = [f"        {p} & " + " & ".join(coordinate(p, k) for k in (CW, HW, SLOPE, BW, CH)) + r" \\" for p in FITS]
write("supplement_fits.tex", r"""\begin{table}[htb]
    \centering
    \caption{Costs and fitted-target AARDs of the six fits, each the lower-cost of two converged starts.
    F1--F3 and F6 fit the 141 base targets; F4 and F5 add Matin's 18 \ce{HCO3- + CO3^2-} pool targets (159 targets).
    F6 uses the source reaction laws and \(u_{\COtwo}/k_{\mathrm{B}}=\SI{169.21}{\kelvin}\).
    The species AARD of F4 and F5 includes the pool targets.
    The last column is the relative cost difference between the two starts.}
    \label{tab:s-fits}
    \begin{tabular}{@{}lllrrrrrrr@{}}
        \toprule
        Fit & Born term & Pool & \(n\) & \(C_p\) & \(C_x\) & \(C\) & \makecell{AARD\\\(p\), \%} & \makecell{AARD\\\(x\), \%} & \makecell{Start\\difference} \\
        \midrule
""" + "\n".join(cost_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}

\begin{table}[htb]
    \centering
    \caption{Fitted binary interaction parameters of the six fits; ``(bound)'' marks a coordinate at a bound.
    \(k_{\MEAH,\HtwoO}\) is the value at \SI{313.15}{\kelvin}, and \(b\) is in kelvin.}
    \label{tab:s-coordinates}
    \begin{tabular}{@{}lrrrrr@{}}
        \toprule
        Fit & """ + " & ".join(SYMBOL[k] for k in (CW, HW, SLOPE, BW, CH)) + r""" \\
        \midrule
""" + "\n".join(coord_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")

# Supplement: fitted-target AARD by source and species.
by_source = {(r["problem"], r["group"]): r for r in rows("fit-aard-by-source-species.csv")
             if r["start"] == summary[r["problem"]]["lower_complete_start"]}
f6 = {(r["source"], r["species"]): r for r in rows("f6-aard-by-source-species.csv") if r["start"] == "A"}
assert summary["F6"]["lower_complete_start"] == "A"
targets = [("Hilliard 2008", "\\(p_{\\COtwo}\\)", "Hilliard2008:pCO2", ("Hilliard2008", "pCO2")),
           ("Jou et al.", "\\(p_{\\COtwo}\\)", "Jou1995:pCO2", ("Jou1995", "pCO2")),
           ("B\\\"ottinger et al.", "\\ce{MEA + MEAH+}", "Bottinger2008:MEA + MEAH+", ("Bottinger2008", "MEA + MEAH+")),
           ("B\\\"ottinger et al.", "\\MEACOO", "Bottinger2008:MEACOO-", ("Bottinger2008", "MEACOO-")),
           ("B\\\"ottinger et al.", "\\ce{HCO3- + CO3^2-}", "Bottinger2008:HCO3-", ("Bottinger2008", "HCO3-")),
           ("Matin et al.", "\\MEA", "Matin2012:MEA", ("Matin2012", "MEA")),
           ("Matin et al.", "\\MEAH", "Matin2012:MEAH+", ("Matin2012", "MEAH+")),
           ("Matin et al.", "\\MEACOO", "Matin2012:MEACOO-", ("Matin2012", "MEACOO-")),
           ("Matin et al.", "\\ce{HCO3- + CO3^2-}", "Matin2012:HCO3-", None)]
source_rows = []
for source, quantity, group, f6_key in targets:
    n = by_source[("F4", group)]["n"]
    cells = [num(by_source[(p, group)]["aard_percent"]) if (p, group) in by_source else "--" for p in FITS[:5]]
    cells.append(num(f6[f6_key]["aard_percent"]) if f6_key else "--")
    source_rows.append(f"        {source} & {quantity} & {n} & " + " & ".join(cells) + r" \\")
write("supplement_source_aard.tex", r"""\begin{table}[htb]
    \centering
    \caption{Fitted-target AARD (\%) by source and observable for the six fits.
    The Matin pool is fitted only in F4 and F5; its values for the other fits are in \cref{tab:s-outside}.}
    \label{tab:s-source-aard}
    \begin{tabular}{@{}llrrrrrrr@{}}
        \toprule
        Source & Observable & \(n\) & F1 & F2 & F3 & F4 & F5 & F6 \\
        \midrule
""" + "\n".join(source_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")

# Supplement: conditional correlations.
uncertainty = json.loads((RUN / "conditional-uncertainty.json").read_text())
blocks = []
for p in ("F1", "F2"):
    names = uncertainty[p]["interior_coordinates"]
    matrix = uncertainty[p]["conditional_correlation"]
    blocks.append(f"        \\multicolumn{{6}}{{@{{}}l}}{{\\emph{{{p}, {form[p]}; residual variance {uncertainty[p]['residual_variance']:.4f}, "
                  f"{len(names)} interior parameters}}}} \\\\")
    for name, values in zip(names, matrix):
        cells = [num(v, 3) for v in values] + [""] * (4 - len(values))
        blocks.append(f"        {SYMBOL[name]} & {standard_error(p, name)} & " + " & ".join(cells) + r" \\")
write("supplement_correlations.tex", r"""\begin{table}[htb]
    \centering
    \caption{Conditional standard errors and correlations of the interior parameters of F1 and F2.
    The covariance is \(s^2(J_I^{\mathsf{T}}J_I)^{-1}\), with \(J_I\) the interior columns of the weighted Jacobian in physical units and \(s^2=2C/(n-p)\), \(n=141\).
    Correlation columns follow the row order.
    Parameters at a bound are excluded.
    Residuals are treated as independent although titration species of one sample share an analysis, so the values are conditional and indicative.}
    \label{tab:s-correlations}
    \begin{tabular}{@{}lrrrrr@{}}
        \toprule
        Parameter & SE & \multicolumn{4}{c}{Correlation} \\
        \midrule
""" + "\n".join(blocks) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")

# Supplement: outside-fit scores by source.
outside = [("Measured pressure, \\SI{80}{\\degreeCelsius}", "canonical 80C 21"), ("\\quad Jou et al.", "Jou 80C"),
           ("B\\\"ottinger et al.\\ species, \\SI{80}{\\degreeCelsius}", "Bottinger 80C species"),
           ("Wagner et al., near \\SI{353}{\\kelvin}", "Wagner near 353.15K"),
           ("Wagner et al., near \\SI{392}{\\kelvin}", "Wagner near 392.15K"),
           ("Measured pressure, 100--\\SI{120}{\\degreeCelsius}", "100-120C"), ("\\quad Jou et al.", "100-120C Jou1995"),
           ("\\quad Ma'mun et al.", "100-120C Mamun2005"), ("\\quad Xu and Rochelle", "100-120C Xu2011"),
           ("Measured pressure, 40--\\SI{80}{\\degreeCelsius}", "pooled 40-80C"), ("\\quad Aronu et al.", "pooled 40-80C Aronu2011"),
           ("\\quad Hilliard", "pooled 40-80C Hilliard2008"), ("\\quad Idris et al.", "pooled 40-80C Idris2014"),
           ("\\quad Jou et al.", "pooled 40-80C Jou1995"), ("Aronu et al., 15 wt\\% \\MEA", "transfer 15wt%"),
           ("Aronu et al., 45 wt\\% \\MEA", "transfer 45wt%"), ("Matin pool, \\SI{20}{\\degreeCelsius}", "Matin pool report-only")]
outside_rows = [f"        {label} & {scores[('F1', key)]['rows']} & " + " & ".join(
    f"{aard(p, key)} & {num(scores[(p, key)]['mean_ln'], 3)}" for p in ("F1", "F2", "F6")) + r" \\" for label, key in outside]
write("supplement_outside_fit.tex", r"""\begin{table}[htb]
    \centering
    \caption{Comparisons outside the fit for F1, F2 and F6: AARD (\%) and mean \(\ln(y_{\mathrm{calc}}/y_{\mathrm{obs}})\).
    Indented rows divide the group above by source.
    Three Xu and Rochelle rows at 120.4--\SI{121.8}{\degreeCelsius} lie outside the declared 293.15--\SI{393.15}{\kelvin} domain of the reaction correlations and were not evaluated.}
    \label{tab:s-outside}
    \begin{tabular}{@{}lrrrrrrr@{}}
        \toprule
        Group & \(n\) & \multicolumn{2}{c}{F1} & \multicolumn{2}{c}{F2} & \multicolumn{2}{c}{F6} \\
        & & AARD & mean ln & AARD & mean ln & AARD & mean ln \\
        \midrule
""" + "\n".join(outside_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")

# Supplement: Jakobsen carbonate share and loaded density.
share = {(r["problem"], r["temperature_C"], r["loading"]): r for r in jakobsen}
share_rows = [f"        {num(r['temperature_C'], 0)} & {num(r['loading'])} & {num(r['observed_carbonate_share'], 4)} & "
              + " & ".join(num(share[(p, r['temperature_C'], r['loading'])]["ratio"]) for p in ("F1", "F2", "F6"))
              + f" & {'yes' if r['summary_included'] == 'True' else 'no'} \\\\" for r in jakobsen if r["problem"] == "F1"]
dens = {(r["problem"], r["state"]): r for r in density}
density_rows = [f"        {num(r['temperature_C'], 0)} & {num(r['loading_mol_co2_per_mol_mea'], 1)} & {num(r['amundsen_density_g_cm3'], 4)} & "
                + " & ".join(f"{num(dens[(p, r['state'])]['model_density_g_cm3'], 4)} & {num(dens[(p, r['state'])]['deviation_percent'], 1)}"
                             for p in ("F1", "F2", "F6")) + r" \\" for r in density if r["problem"] == "F1"]
write("supplement_carbonate_density.tex", r"""\begin{table}[htb]
    \centering
    \caption{Carbonate share of dissolved carbon, \(x_{\COthree}/(x_{\HCOthree}+x_{\COthree}+x_{\MEACOO}+x_{\COtwo})\) as reported by Jakobsen et al., and the calculated/observed ratio for each fit.
    Loadings are the printed \emph{maxload} values; the source dilution and loading definitions are unresolved.
    The point at \SI{40}{\degreeCelsius} and loading 0.21 is excluded from the summary range of the main text.}
    \label{tab:s-carbonate}
    \begin{tabular}{@{}rrrrrrc@{}}
        \toprule
        \(T\) (\si{\degreeCelsius}) & \(\alpha\) & Observed & F1 & F2 & F6 & In summary \\
        \midrule
""" + "\n".join(share_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}

\begin{table}[htb]
    \centering
    \caption{Loaded-solution density of 30 wt\% \MEA (\COtwo-free basis) from Amundsen et al.\ and the homogeneous-liquid density of each fit at an assumed \SI{101325}{\pascal}; the source does not report the measurement pressure.
    Densities in \si{\gram\per\cubic\centi\metre}; deviations in percent.}
    \label{tab:s-density}
    \begin{tabular}{@{}rrrrrrrrr@{}}
        \toprule
        \(T\) (\si{\degreeCelsius}) & \(\alpha\) & Measured & \multicolumn{2}{c}{F1} & \multicolumn{2}{c}{F2} & \multicolumn{2}{c}{F6} \\
        \midrule
""" + "\n".join(density_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")

# Supplement: Born-off decomposition statistics.
checks = json.loads((RUN / "activity-contributions/checks.json").read_text())["falsifiers"]
third_rows = [f"        {num(r['T_K'] - 273.15, 0)} & {r['third']} & {r['n']} & {num(r['mean_phi'], 3)} \\\\"
              for r in checks["C"]["loading_thirds"] if r["parent"] == "adopted"]
write("supplement_decomposition.tex", r"""\begin{table}[htb]
    \centering
    \caption{Mean offset fraction \(\phi\) of the Born-off refit F3 relative to F1, by loading third of the fitted pressure states (third 1 is the lowest loading).
    \(\phi=1\) means the non-Born activity changes of the refit fully offset the removed Born contribution to \(Q\); \(\phi=0\) means no offset.}
    \label{tab:s-phi}
    \begin{tabular}{@{}rrrr@{}}
        \toprule
        \(T\) (\si{\degreeCelsius}) & Third & \(n\) & Mean \(\phi\) \\
        \midrule
""" + "\n".join(third_rows) + r"""
        \bottomrule
    \end{tabular}
\end{table}
""")
print("wrote", sorted(p.name for p in TABLES.glob("*.tex")))
