"""Generate the reviewed 34-entry table from the corrected source manifest.

Usage: python scripts/supplement_data_inventory.py MANIFEST [ZOTERO_BIB]
Output: tables/supplement_data_inventory.tex. No observations are admitted.
"""
import csv
import hashlib
import re
import sys
from pathlib import Path

SELECTED = '''Wong2015 Idris2014 Amundsen2009 Fan2009 Jou1995 Aronu2011
Wagner2013 Park2002 Mamun2005 Tong2012 Dugas2011 Dugas2009 Xu2011
Hilliard2008 Bottinger2008 Jakobsen2005 Matin2012 Wong2016 Yamada2012
Kim2007 Kim2014 Mathonat1998 Arcis2011 Vinjarapu2024 Han2012 Hartono2014
Jayarathna2013 Weiland1998 Weiland1997 Ganesan2026 Concepcion2023
Karunarathne2020 Won16c Sob16b'''.split()
SALT = {'Wong2015', 'Wong2016', 'Won16c'}
manifest = Path(sys.argv[1]).resolve()
bib = Path(sys.argv[2] if len(sys.argv) > 2 else '~/Zotero/exports/references.bib').expanduser()
entries = {m.group(1): m.group(0) for m in re.finditer(
    r'^@\w+\{([^,]+),.*?^\}\s*$', bib.read_text(), re.S | re.M)}

def field(entry, name):
    m = re.search(r'^\s*' + name + r'\s*=\s*\{(.*?)\},?\s*$', entry, re.M)
    return m.group(1) if m else ''

def doi(value):
    return re.sub(r'^https?://(?:dx\.)?doi.org/', '', value.strip().lower())

by_doi = {}
for key, entry in entries.items():
    value = doi(field(entry, 'doi'))
    if value:
        by_doi.setdefault(value, []).append(key)

with manifest.open(newline='') as handle:
    rows = list(csv.DictReader(handle))
lookup = {r['source_key']: r for r in rows}
assert len(SELECTED) == len(set(SELECTED)) == 34
assert len(lookup) == len(rows)
assert sum(r['evidence_level'] == 'discovery_metadata_only' for r in rows) == 88
assert all(lookup[k]['evidence_level'] in {
    'primary_passage_or_table_verified', 'primary_database_metadata_verified'} for k in SELECTED)

def tex(value):
    # Escape without rewriting source wording or whitespace. URLs own their breaks.
    replacements = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%',
                    '$': r'\$', '#': r'\#', '{': r'\{', '}': r'\}',
                    '_': r'\_', '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}
    result = []
    for part in re.split(r'(https?://[^\s;]+)', value):
        if part.startswith(('http://', 'https://')):
            result.append(r'\url{' + part + '}')
            continue
        for token in re.split(r'(\s+)', part):
            long_token = len(token) > 12 and any(c in token for c in '/_.-')
            for char in token:
                result.append(replacements.get(char, char))
                if char in ';,:' or (long_token and char in '/_.-'):
                    result.append(r'\allowbreak{}')
    return ''.join(result)

def paragraphs(parts):
    return r'\par '.join(tex(p) for p in parts if p)

def caveats(row):
    # Omit workflow receipts already owned by the manifest; retain source caveats.
    sentences = re.split(r'(?<=\.)\s+', row['inventory_notes'])
    receipt = ('2026-09-30 extraction:', 'Live Zotero ', 'Existing74 rows matched',
               'No model-basis conversion', 'Independent read-only review',
               'Confirms transcription/provenance')
    kept = [s for s in sentences if not s.startswith(receipt)
            and not (s.startswith('All ') and ('checked' in s or 're-read' in s))]
    return ' '.join(kept)

caption = (r'Non-exhaustive inventory of 34 publication entries with confirmed near-30 wt\% scope '
           r'and primary-passage/table or primary-database evidence. The 88 discovery-only entries '
           r'in the source manifest are excluded from verified coverage. Mass fraction, molality '
           r'(per kg water or solution), and molarity remain distinct reported bases; no equivalence '
           r'is assumed. The three marked Wong studies contain sodium perchlorate reference salt; '
           r'NMR dilution and additives can change the final liquid composition. Campaign overlap, '
           r'reused states, aggregate and derived quantities are retained as caveats; counts are not '
           r'additive across publications or properties. Blank source fields are rendered as unverified, '
           r'never zero. Extraction does not admit observations to parameter fitting. Temperature '
           r'envelopes are in K; reported property-specific temperatures retain their stated units.')
headers = ['Reference', 'Quantity and method', 'MEA composition', 'Temperature / K',
           'Loading and pressure', 'Observation counts', 'Evidence and extraction', 'Locator and caveats']
head = ' & '.join(r'\textbf{' + h + '}' for h in headers) + r' \\'
output = [
    '% Generated by scripts/supplement_data_inventory.py; do not hand-edit values.',
    '% Source manifest SHA-256: ' + hashlib.sha256(manifest.read_bytes()).hexdigest(),
    '% Requires longtable, pdflscape, array, booktabs, xurl and a citation package.',
    r'\begin{landscape}', r'\begingroup', r'\fontsize{7}{8.4}\selectfont',
    r'\setlength{\tabcolsep}{2pt}', r'\setlength{\LTcapwidth}{24.5cm}', r'\renewcommand{\arraystretch}{1.08}',
    r'\begin{longtable}{@{}' + ''.join(r'>{\raggedright\arraybackslash}p{' + str(w) + 'cm}'
                                      for w in [1.8, 2.7, 3.1, 1.8, 2.2, 2.6, 1.5, 7.9]) + r'@{}}',
    r'\caption{' + caption + r'}\label{tab:s4-data-inventory}\\',
    r'\toprule', head, r'\midrule', r'\endfirsthead',
    r'\multicolumn{8}{l}{\tablename~\thetable{} (continued)}\\',
    r'\toprule', head, r'\midrule', r'\endhead',
    r'\midrule\multicolumn{8}{r}{Continued on next page}\\', r'\endfoot',
    r'\bottomrule', r'\endlastfoot']
missing = []
for source in SELECTED:
    r = lookup[source]
    candidates = by_doi.get(doi(r['doi']), []) if r['doi'] else []
    key = r['citation_key'] if r['citation_key'] in candidates else (candidates[0] if candidates else '')
    # Hilliard's dissertation has no DOI: check its supplied key against the title.
    if not r['doi'] and r['citation_key'] in entries:
        normalize = lambda s: re.sub(r'[^a-z0-9]', '', s.lower())
        if normalize(field(entries[r['citation_key']], 'title')) == normalize(r['title']):
            key = r['citation_key']
    if not key:
        missing.append(source)
    label = {'Won16c': 'Wong 2016', 'Sob16b': 'Sobrino 2016'}.get(
        source, re.sub(r'(?<=[A-Za-z])(?=\d{4}$)', ' ', source))
    reference = tex(label) + (r' \cite{' + key + '}' if key else r' (citation key unavailable)')
    if r['doi']:
        reference += r'\par DOI: \url{' + r['doi'] + '}'
    if source in SALT:
        reference += r'\par\textbf{Salt-containing study}'
    temperatures = r['temperature_min_K'] + ('--' + r['temperature_max_K']
                    if r['temperature_max_K'] != r['temperature_min_K'] else '')
    cells = [reference,
             paragraphs([r['property_family'], r['measurement_method']]),
             paragraphs([r['concentration_reported'], 'Basis: ' + r['concentration_basis']]),
             paragraphs([temperatures + ' K' if r['temperature_min_K'] else 'Unverified',
                         'Reported: ' + r['temperature_reported']]),
             paragraphs(['Loading: ' + (r['loading_range_reported'] or 'unverified'),
                         'Pressure: ' + (r['pressure_range_reported'] or 'unverified')]),
             paragraphs(['Near-30 wt% published: ' + (r['near_30wt_point_count'] or 'unverified'),
                         'Retained: ' + (r['retained_point_count'] or 'unverified'),
                         'Published record: ' + (r['published_point_count'] or 'unverified'),
                         'Count basis: ' + (r['point_count_scope'] or 'unverified')]),
             paragraphs([r['access_status'], r['evidence_level'], r['repo_extraction_status']]),
             paragraphs([r['evidence_locator'], caveats(r), r['notes']])]
    output += ['% Entry: ' + source, ' & '.join(cells) + r' \\', r'\addlinespace']
output += [r'\end{longtable}', r'\endgroup', r'\end{landscape}', '']
target = Path(__file__).resolve().parents[1] / 'tables/supplement_data_inventory.tex'
target.write_text('\n'.join(output))
print(f'{target}: {len(SELECTED)} entries; missing citation keys: {", ".join(missing) or "none"}')
